/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedWelcomeImport } from './routes/_protected/welcome'
import { Route as ProtectedReportsImport } from './routes/_protected/reports'
import { Route as ProtectedCompaniesImport } from './routes/_protected/companies'
import { Route as ProtectedReportDetailReportIdImport } from './routes/_protected/report-detail.$reportId'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedWelcomeRoute = ProtectedWelcomeImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedReportsRoute = ProtectedReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedCompaniesRoute = ProtectedCompaniesImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedReportDetailReportIdRoute =
  ProtectedReportDetailReportIdImport.update({
    id: '/report-detail/$reportId',
    path: '/report-detail/$reportId',
    getParentRoute: () => ProtectedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_protected/companies': {
      id: '/_protected/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof ProtectedCompaniesImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/welcome': {
      id: '/_protected/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof ProtectedWelcomeImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/report-detail/$reportId': {
      id: '/_protected/report-detail/$reportId'
      path: '/report-detail/$reportId'
      fullPath: '/report-detail/$reportId'
      preLoaderRoute: typeof ProtectedReportDetailReportIdImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteChildren {
  ProtectedCompaniesRoute: typeof ProtectedCompaniesRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedWelcomeRoute: typeof ProtectedWelcomeRoute
  ProtectedReportDetailReportIdRoute: typeof ProtectedReportDetailReportIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCompaniesRoute: ProtectedCompaniesRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedWelcomeRoute: ProtectedWelcomeRoute,
  ProtectedReportDetailReportIdRoute: ProtectedReportDetailReportIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/companies': typeof ProtectedCompaniesRoute
  '/reports': typeof ProtectedReportsRoute
  '/welcome': typeof ProtectedWelcomeRoute
  '/report-detail/$reportId': typeof ProtectedReportDetailReportIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/companies': typeof ProtectedCompaniesRoute
  '/reports': typeof ProtectedReportsRoute
  '/welcome': typeof ProtectedWelcomeRoute
  '/report-detail/$reportId': typeof ProtectedReportDetailReportIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/companies': typeof ProtectedCompaniesRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/_protected/welcome': typeof ProtectedWelcomeRoute
  '/_protected/report-detail/$reportId': typeof ProtectedReportDetailReportIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/companies'
    | '/reports'
    | '/welcome'
    | '/report-detail/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/companies'
    | '/reports'
    | '/welcome'
    | '/report-detail/$reportId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/companies'
    | '/_protected/reports'
    | '/_protected/welcome'
    | '/_protected/report-detail/$reportId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/companies",
        "/_protected/reports",
        "/_protected/welcome",
        "/_protected/report-detail/$reportId"
      ]
    },
    "/_protected/companies": {
      "filePath": "_protected/companies.tsx",
      "parent": "/_protected"
    },
    "/_protected/reports": {
      "filePath": "_protected/reports.tsx",
      "parent": "/_protected"
    },
    "/_protected/welcome": {
      "filePath": "_protected/welcome.tsx",
      "parent": "/_protected"
    },
    "/_protected/report-detail/$reportId": {
      "filePath": "_protected/report-detail.$reportId.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
