/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserIdReportsImport } from './routes/$userId.reports'
import { Route as UserIdCompaniesImport } from './routes/$userId.companies'
import { Route as UserIdReportDetailReportIdImport } from './routes/$userId.report-detail.$reportId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIdReportsRoute = UserIdReportsImport.update({
  id: '/$userId/reports',
  path: '/$userId/reports',
  getParentRoute: () => rootRoute,
} as any)

const UserIdCompaniesRoute = UserIdCompaniesImport.update({
  id: '/$userId/companies',
  path: '/$userId/companies',
  getParentRoute: () => rootRoute,
} as any)

const UserIdReportDetailReportIdRoute = UserIdReportDetailReportIdImport.update(
  {
    id: '/$userId/report-detail/$reportId',
    path: '/$userId/report-detail/$reportId',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$userId/companies': {
      id: '/$userId/companies'
      path: '/$userId/companies'
      fullPath: '/$userId/companies'
      preLoaderRoute: typeof UserIdCompaniesImport
      parentRoute: typeof rootRoute
    }
    '/$userId/reports': {
      id: '/$userId/reports'
      path: '/$userId/reports'
      fullPath: '/$userId/reports'
      preLoaderRoute: typeof UserIdReportsImport
      parentRoute: typeof rootRoute
    }
    '/$userId/report-detail/$reportId': {
      id: '/$userId/report-detail/$reportId'
      path: '/$userId/report-detail/$reportId'
      fullPath: '/$userId/report-detail/$reportId'
      preLoaderRoute: typeof UserIdReportDetailReportIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$userId/companies': typeof UserIdCompaniesRoute
  '/$userId/reports': typeof UserIdReportsRoute
  '/$userId/report-detail/$reportId': typeof UserIdReportDetailReportIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$userId/companies': typeof UserIdCompaniesRoute
  '/$userId/reports': typeof UserIdReportsRoute
  '/$userId/report-detail/$reportId': typeof UserIdReportDetailReportIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$userId/companies': typeof UserIdCompaniesRoute
  '/$userId/reports': typeof UserIdReportsRoute
  '/$userId/report-detail/$reportId': typeof UserIdReportDetailReportIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$userId/companies'
    | '/$userId/reports'
    | '/$userId/report-detail/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$userId/companies'
    | '/$userId/reports'
    | '/$userId/report-detail/$reportId'
  id:
    | '__root__'
    | '/'
    | '/$userId/companies'
    | '/$userId/reports'
    | '/$userId/report-detail/$reportId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserIdCompaniesRoute: typeof UserIdCompaniesRoute
  UserIdReportsRoute: typeof UserIdReportsRoute
  UserIdReportDetailReportIdRoute: typeof UserIdReportDetailReportIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserIdCompaniesRoute: UserIdCompaniesRoute,
  UserIdReportsRoute: UserIdReportsRoute,
  UserIdReportDetailReportIdRoute: UserIdReportDetailReportIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$userId/companies",
        "/$userId/reports",
        "/$userId/report-detail/$reportId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$userId/companies": {
      "filePath": "$userId.companies.tsx"
    },
    "/$userId/reports": {
      "filePath": "$userId.reports.tsx"
    },
    "/$userId/report-detail/$reportId": {
      "filePath": "$userId.report-detail.$reportId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
