/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ReportsUserIdImport } from './routes/reports.$userId'
import { Route as CompaniesUserIdImport } from './routes/companies.$userId'
import { Route as ReportDetailUserIdReportIdImport } from './routes/report-detail.$userId.$reportId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReportsUserIdRoute = ReportsUserIdImport.update({
  id: '/reports/$userId',
  path: '/reports/$userId',
  getParentRoute: () => rootRoute,
} as any)

const CompaniesUserIdRoute = CompaniesUserIdImport.update({
  id: '/companies/$userId',
  path: '/companies/$userId',
  getParentRoute: () => rootRoute,
} as any)

const ReportDetailUserIdReportIdRoute = ReportDetailUserIdReportIdImport.update(
  {
    id: '/report-detail/$userId/$reportId',
    path: '/report-detail/$userId/$reportId',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/companies/$userId': {
      id: '/companies/$userId'
      path: '/companies/$userId'
      fullPath: '/companies/$userId'
      preLoaderRoute: typeof CompaniesUserIdImport
      parentRoute: typeof rootRoute
    }
    '/reports/$userId': {
      id: '/reports/$userId'
      path: '/reports/$userId'
      fullPath: '/reports/$userId'
      preLoaderRoute: typeof ReportsUserIdImport
      parentRoute: typeof rootRoute
    }
    '/report-detail/$userId/$reportId': {
      id: '/report-detail/$userId/$reportId'
      path: '/report-detail/$userId/$reportId'
      fullPath: '/report-detail/$userId/$reportId'
      preLoaderRoute: typeof ReportDetailUserIdReportIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/$userId': typeof CompaniesUserIdRoute
  '/reports/$userId': typeof ReportsUserIdRoute
  '/report-detail/$userId/$reportId': typeof ReportDetailUserIdReportIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/$userId': typeof CompaniesUserIdRoute
  '/reports/$userId': typeof ReportsUserIdRoute
  '/report-detail/$userId/$reportId': typeof ReportDetailUserIdReportIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/companies/$userId': typeof CompaniesUserIdRoute
  '/reports/$userId': typeof ReportsUserIdRoute
  '/report-detail/$userId/$reportId': typeof ReportDetailUserIdReportIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies/$userId'
    | '/reports/$userId'
    | '/report-detail/$userId/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies/$userId'
    | '/reports/$userId'
    | '/report-detail/$userId/$reportId'
  id:
    | '__root__'
    | '/'
    | '/companies/$userId'
    | '/reports/$userId'
    | '/report-detail/$userId/$reportId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesUserIdRoute: typeof CompaniesUserIdRoute
  ReportsUserIdRoute: typeof ReportsUserIdRoute
  ReportDetailUserIdReportIdRoute: typeof ReportDetailUserIdReportIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesUserIdRoute: CompaniesUserIdRoute,
  ReportsUserIdRoute: ReportsUserIdRoute,
  ReportDetailUserIdReportIdRoute: ReportDetailUserIdReportIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/companies/$userId",
        "/reports/$userId",
        "/report-detail/$userId/$reportId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/companies/$userId": {
      "filePath": "companies.$userId.tsx"
    },
    "/reports/$userId": {
      "filePath": "reports.$userId.tsx"
    },
    "/report-detail/$userId/$reportId": {
      "filePath": "report-detail.$userId.$reportId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
